pipeline {
    agent any
    parameters {
        string defaultValue: 'master',description: 'Branch to Build', name: 'BRANCH', trim: true
    }
    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'git_ssh_key', branch: params.BRANCH, url: 'https://github.com/vivekgupta8983/simple-java-maven-app.git'
            }
        }
        stage('Build') {
            steps {
                sh '/opt/maven/bin/mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh '/opt/maven/bin/mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    post {
        always {
            cleanWs()
        }
    }
    }
}
